syntax = "proto3";

package stock;

service StockService {
    rpc Simulate(StockRequest) returns (stream StockResponse);
}

message StockRequest {
    string ticker = 1;
    string interval = 2;
    int32 num_paths =  3;
    int32 num_steps = 4;
}

 message StockHistory {
    string timestamp = 1;
    double steps = 2;
 }

message StockHistoryResponse {
  repeated StockHistory stockhistories = 1;
}

message Path {
    repeated double steps = 1;
}

message StockResponse {
    repeated Path paths = 1;
}
